version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - zookeeper_network

  kafka_broker:
    image: wurstmeister/kafka:latest #confluentinc/cp-kafka:5.2.1
    container_name: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://kafka_broker:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:29092,PLAINTEXT_HOST://kafka_broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - zookeeper_network

  nimbus:
    image: storm
    container_name: storm_nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    networks:
      - zookeeper_network
    ports:
      - 6627:6627
    restart: always

  supervisor:
    image: storm
    container_name: storm_supervisor
    command: storm supervisor
    ports:
      - 6700:6700
      - 6701:6701
      - 6702:6702
    depends_on:
      - nimbus
      - zookeeper
    networks:
      - zookeeper_network

  storm_ui:
    image: storm
    container_name: storm_ui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
      - supervisor
    ports:
      - 8081:8080
    networks:
      - zookeeper_network
      #- datasleuth_portfolio_nginx-proxy
    environment:
      - VIRTUAL_HOST=storm.datasleuth.agency

  swarm_ui:
    image: dockersamples/visualizer
    container_name: viz
    ports:
      - 8083:8080
    networks:
      - zookeeper_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  zookeeper_network:
  #datasleuth_portfolio_nginx-proxy:
  # external:
  #  name: datasleuth_portfolio_nginx-proxy
  